// Originally auto-generated by Lovable, then modified deliberately.
//
// The generated version imported the browser Supabase client and called
// `supabase.auth.setSession(result.tokens)`, which persisted BOTH tokens to
// localStorage under `sb-<ref>-auth-token`. That is exactly what this app must
// not do: the refresh token belongs in an httpOnly cookie the browser's JS
// cannot read.
//
// So this wrapper now just returns the tokens to its caller. The caller hands
// them to the `completeOAuthSignIn` server action, which validates them,
// stores the refresh token as an httpOnly cookie, and returns only a
// short-lived access token to be held in memory.
//
// If Lovable regenerates this file, that localStorage write comes back — check
// this file after any Lovable sync.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export type OAuthResult = {
  /** Present when the provider bounced us elsewhere; nothing to do here. */
  redirected?: boolean;
  error?: Error | { message: string };
  tokens?: { access_token: string; refresh_token: string };
};

export const lovable = {
  auth: {
    /**
     * Starts the OAuth dance and returns the raw result. The tokens are handed
     * back to the caller rather than persisted here — see the note above.
     */
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ): Promise<OAuthResult> => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: { ...opts?.extraParams },
      });
      return result as OAuthResult;
    },
  },
};
